erDiagram
    USER {
        string id PK "prefix: user"
        string first_name "nullable, searchable"
        string last_name "nullable, searchable"
        string email "searchable"
        string avatar_url "nullable"
        jsonb metadata "nullable"
    }
    
    INVITE {
        string id PK
        string email "Unique"
        boolean accepted
        string token
        timestamp expires_at
        jsonb metadata "nullable"
    }
